name: weather_app
description: GFC weather application
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  path_provider: ^2.0.11
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  json_annotation: ^4.7.0
  responsive_builder: ^0.7.0
  logger: ^2.2.0
  toastification: ^1.2.1
  dio: ^5.4.1
  go_router: ^13.2.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  quiver: ^3.2.1
  validators: ^3.0.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  animations: ^2.0.11
  page_transition: ^2.1.0
  internet_connection_checker_plus: ^2.2.0
  connectivity_wrapper: ^1.1.4
  domain_models:
    path: packages/domain_models
  open_weather_repository:
    path: packages/open_weather_repository


dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/ng.json
  uses-material-design: true
  generate: true
  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaRegular.ttf
        - asset: assets/fonts/LufgaItalic.ttf
          style: italic
        - asset: assets/fonts/LufgaBold.ttf
          weight: 700
        - asset: assets/fonts/LufgaExtraBold.ttf
          weight: 900
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 500
        - asset: assets/fonts/LufgaExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/LufgaBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/LufgaMediumItalic.ttf
          weight: 500
          style: italic